// LearningMemoryPanel.tsx
// V2 H9.5: 学习记忆管理面板 — 查看/管理纠正记录与模式学习
//
// 功能:
//   - 双 Tab 切换（纠正记录 / 模式学习）
//   - 纠正记录列表（id/timestamp/originalCommand/userCorrection/correctedParams/pattern）
//   - 模式学习列表（pattern/occurrences/lastSeen/autoGenerated）
//   - 单条删除 + 一键清除全部（H9.6 隐私保护）
//   - 计划校验入口（H9.4 错误避免 — 输入 steps 检测历史风险）
//
// API 契约（见 server/routes/learning-memory.js）:
//   GET    /api/learning-memory/corrections?limit=50
//   GET    /api/learning-memory/patterns
//   DELETE /api/learning-memory/corrections/:id
//   DELETE /api/learning-memory/clear
//   POST   /api/learning-memory/check   body: { steps: [...] }

import { useState, useEffect, useCallback } from "react";

interface Correction {
  id: string;
  timestamp: string;
  originalCommand: string;
  originalParams?: Record<string, unknown>;
  userCorrection?: string;
  correctedParams?: Record<string, unknown>;
  context?: Record<string, unknown>;
  pattern?: string;
}

interface Pattern {
  id?: string;
  pattern: string;
  occurrences: number;
  lastSeen?: string;
  autoGenerated?: boolean;
  suggestedParams?: Record<string, unknown>;
}

interface LearningMemoryPanelProps {
  lang?: "zh-CN" | "en-US";
  embedded?: boolean;
}

type Tab = "corrections" | "patterns";

export default function LearningMemoryPanel({ lang = "zh-CN", embedded = false }: LearningMemoryPanelProps) {
  const [activeTab, setActiveTab] = useState<Tab>("corrections");
  const [corrections, setCorrections] = useState<Correction[]>([]);
  const [patterns, setPatterns] = useState<Pattern[]>([]);
  const [loading, setLoading] = useState(false);
  const [statusMsg, setStatusMsg] = useState<string>("");
  const [checkInput, setCheckInput] = useState<string>("");
  const [checkResult, setCheckResult] = useState<any>(null);

  const loadCorrections = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/learning-memory/corrections?limit=50");
      const data = await res.json();
      if (data.ok) {
        setCorrections(data.corrections || []);
      }
    } catch (e) {
      console.error("[LM] Load corrections failed:", e);
    } finally {
      setLoading(false);
    }
  }, []);

  const loadPatterns = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/learning-memory/patterns");
      const data = await res.json();
      if (data.ok) {
        setPatterns(data.patterns || []);
      }
    } catch (e) {
      console.error("[LM] Load patterns failed:", e);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (activeTab === "corrections") loadCorrections();
    else loadPatterns();
  }, [activeTab, loadCorrections, loadPatterns]);

  // 删除单条纠正
  const handleDelete = async (id: string) => {
    if (!confirm(`确定删除纠正记录 ${id}？`)) return;
    try {
      const res = await fetch(`/api/learning-memory/corrections/${id}`, { method: "DELETE" });
      const data = await res.json();
      if (data.ok) {
        setStatusMsg(`✅ ${lang === "zh-CN" ? "已删除" : "Deleted"}: ${id}`);
        loadCorrections();
      } else {
        setStatusMsg(`❌ ${data.error}`);
      }
    } catch (e: any) {
      setStatusMsg(`❌ ${e.message}`);
    }
  };

  // H9.6: 清除所有学习记忆
  const handleClearAll = async () => {
    if (!confirm(lang === "zh-CN"
      ? "⚠️ 确定清除所有学习记忆？此操作不可恢复，所有纠正记录和模式学习将被删除。"
      : "⚠️ Clear ALL learning memory? This is irreversible.")) return;
    try {
      const res = await fetch("/api/learning-memory/clear", { method: "DELETE" });
      const data = await res.json();
      if (data.ok) {
        setStatusMsg(`✅ ${lang === "zh-CN" ? "已清除所有学习记忆" : "All learning memory cleared"}`);
        setCorrections([]);
        setPatterns([]);
      } else {
        setStatusMsg(`❌ ${data.error}`);
      }
    } catch (e: any) {
      setStatusMsg(`❌ ${e.message}`);
    }
  };

  // H9.4: 计划校验
  const handleCheck = async () => {
    try {
      const steps = JSON.parse(checkInput);
      if (!Array.isArray(steps)) {
        setStatusMsg("❌ steps 必须是数组");
        return;
      }
      const res = await fetch("/api/learning-memory/check", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ steps }),
      });
      const data = await res.json();
      if (data.ok) {
        setCheckResult(data);
        setStatusMsg(data.hasRisk
          ? `⚠️ ${lang === "zh-CN" ? "检测到历史风险" : "History risk detected"}: ${data.warnings?.length || 0} ${lang === "zh-CN" ? "条警告" : "warnings"}`
          : `✅ ${lang === "zh-CN" ? "无历史风险" : "No history risk"}`);
      } else {
        setStatusMsg(`❌ ${data.error}`);
      }
    } catch (e: any) {
      setStatusMsg(`❌ JSON ${lang === "zh-CN" ? "格式错误" : "parse error"}: ${e.message}`);
    }
  };

  // 3 秒后清除状态消息
  useEffect(() => {
    if (statusMsg) {
      const timer = setTimeout(() => setStatusMsg(""), 3000);
      return () => clearTimeout(timer);
    }
  }, [statusMsg]);

  const formatTime = (ts: string) => {
    try {
      return new Date(ts).toLocaleString(lang === "zh-CN" ? "zh-CN" : "en-US");
    } catch {
      return ts;
    }
  };

  const paramsToStr = (p?: Record<string, unknown>) => {
    if (!p || Object.keys(p).length === 0) return "-";
    return Object.entries(p).map(([k, v]) => `${k}=${JSON.stringify(v)}`).join(", ");
  };

  return (
    <div className="flex flex-col h-full bg-zinc-950 text-zinc-200">
      {/* 顶部标题 + 操作 */}
      <div className="flex-shrink-0 px-4 py-3 border-b border-zinc-800 flex items-center justify-between">
        <div className="flex items-center gap-2">
          {!embedded && (
            <span className="text-sm font-semibold font-display">
              🧠 {lang === "zh-CN" ? "学习记忆" : "Learning Memory"}
            </span>
          )}
          <span className="text-[10px] font-mono text-zinc-500">
            ({activeTab === "corrections"
              ? `${corrections.length} ${lang === "zh-CN" ? "条纠正" : "corrections"}`
              : `${patterns.length} ${lang === "zh-CN" ? "个模式" : "patterns"}`})
          </span>
        </div>
        <button
          onClick={handleClearAll}
          className="px-2 py-0.5 text-[10px] rounded bg-red-900/30 hover:bg-red-900/50 text-red-400 cursor-pointer"
        >
          {lang === "zh-CN" ? "清除全部" : "Clear All"}
        </button>
      </div>

      {/* Tab 切换 */}
      <div className="flex-shrink-0 px-4 pt-2 flex gap-2 border-b border-zinc-800">
        <button
          onClick={() => setActiveTab("corrections")}
          className={`px-3 py-1.5 text-xs font-semibold border-b-2 transition-colors ${
            activeTab === "corrections"
              ? "border-indigo-500 text-indigo-300"
              : "border-transparent text-zinc-500 hover:text-zinc-300"
          }`}
        >
          {lang === "zh-CN" ? "纠正记录" : "Corrections"}
        </button>
        <button
          onClick={() => setActiveTab("patterns")}
          className={`px-3 py-1.5 text-xs font-semibold border-b-2 transition-colors ${
            activeTab === "patterns"
              ? "border-indigo-500 text-indigo-300"
              : "border-transparent text-zinc-500 hover:text-zinc-300"
          }`}
        >
          {lang === "zh-CN" ? "模式学习" : "Patterns"}
        </button>
      </div>

      {/* 状态消息 */}
      {statusMsg && (
        <div className="flex-shrink-0 px-4 py-1.5 text-[11px] bg-zinc-900/60 text-zinc-400 border-b border-zinc-800">
          {statusMsg}
        </div>
      )}

      {/* 内容区 */}
      <div className="flex-1 overflow-y-auto px-4 py-3">
        {loading ? (
          <div className="text-center text-zinc-500 text-xs py-8">
            {lang === "zh-CN" ? "加载中..." : "Loading..."}
          </div>
        ) : activeTab === "corrections" ? (
          corrections.length === 0 ? (
            <div className="text-center text-zinc-600 text-xs py-8">
              {lang === "zh-CN" ? "暂无纠正记录" : "No corrections yet"}
            </div>
          ) : (
            <div className="flex flex-col gap-2">
              {corrections.slice().reverse().map((c) => (
                <div key={c.id} className="rounded-lg border border-zinc-800 bg-zinc-900/40 p-3">
                  <div className="flex items-center justify-between mb-1.5">
                    <div className="flex items-center gap-2">
                      <span className="text-[10px] font-mono text-indigo-400">{c.id}</span>
                      <span className="text-[10px] text-zinc-600">{formatTime(c.timestamp)}</span>
                      {c.pattern && (
                        <span className="text-[10px] px-1.5 py-0.5 rounded bg-amber-900/30 text-amber-400">
                          {c.pattern}
                        </span>
                      )}
                    </div>
                    <button
                      onClick={() => handleDelete(c.id)}
                      className="text-[10px] text-red-400 hover:text-red-300 cursor-pointer"
                    >
                      ✕
                    </button>
                  </div>
                  <div className="text-xs text-zinc-300 mb-1">
                    <span className="text-zinc-500">{lang === "zh-CN" ? "原命令" : "Original"}: </span>
                    <span className="font-mono text-rose-300">{c.originalCommand}</span>
                  </div>
                  {c.userCorrection && (
                    <div className="text-xs text-zinc-300 mb-1">
                      <span className="text-zinc-500">{lang === "zh-CN" ? "用户纠正" : "Correction"}: </span>
                      <span className="text-emerald-300">{c.userCorrection}</span>
                    </div>
                  )}
                  <div className="text-[11px] text-zinc-500 font-mono">
                    <span className="text-zinc-600">{lang === "zh-CN" ? "原参数" : "Orig params"}: </span>
                    {paramsToStr(c.originalParams)}
                  </div>
                  <div className="text-[11px] text-zinc-500 font-mono">
                    <span className="text-zinc-600">{lang === "zh-CN" ? "正确参数" : "Corrected"}: </span>
                    <span className="text-emerald-400">{paramsToStr(c.correctedParams)}</span>
                  </div>
                </div>
              ))}
            </div>
          )
        ) : patterns.length === 0 ? (
          <div className="text-center text-zinc-600 text-xs py-8">
            {lang === "zh-CN" ? "暂无模式学习记录（≥3 次相同操作自动检测）" : "No patterns yet (auto-detected after 3+ same ops)"}
          </div>
        ) : (
          <div className="flex flex-col gap-2">
            {patterns.map((p, i) => (
              <div key={p.id || i} className="rounded-lg border border-zinc-800 bg-zinc-900/40 p-3">
                <div className="flex items-center justify-between mb-1">
                  <span className="text-xs font-semibold text-amber-300">{p.pattern}</span>
                  {p.autoGenerated && (
                    <span className="text-[10px] px-1.5 py-0.5 rounded bg-amber-900/30 text-amber-400">
                      {lang === "zh-CN" ? "自动" : "auto"}
                    </span>
                  )}
                </div>
                <div className="text-[11px] text-zinc-500 flex gap-3">
                  <span>{lang === "zh-CN" ? "出现" : "Occurred"}: <span className="text-zinc-300">{p.occurrences}</span> {lang === "zh-CN" ? "次" : "times"}</span>
                  {p.lastSeen && <span>{lang === "zh-CN" ? "最近" : "Last"}: {formatTime(p.lastSeen)}</span>}
                </div>
                {p.suggestedParams && Object.keys(p.suggestedParams).length > 0 && (
                  <div className="text-[11px] text-zinc-500 font-mono mt-1">
                    <span className="text-zinc-600">{lang === "zh-CN" ? "建议参数" : "Suggested"}: </span>
                    <span className="text-cyan-400">{paramsToStr(p.suggestedParams)}</span>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* H9.4: 计划校验入口 */}
      <div className="flex-shrink-0 border-t border-zinc-800 p-3 bg-zinc-950">
        <div className="text-[10px] text-zinc-500 mb-1 font-semibold uppercase tracking-wider">
          {lang === "zh-CN" ? "H9.4 错误避免校验" : "H9.4 Error Avoidance Check"}
        </div>
        <div className="flex gap-2">
          <textarea
            value={checkInput}
            onChange={(e) => setCheckInput(e.target.value)}
            placeholder={lang === "zh-CN" ? '粘贴 steps JSON 数组，如 [{"action":"create_wall","params":{}}]' : 'Paste steps JSON array'}
            className="flex-1 text-[11px] font-mono bg-zinc-900 border border-zinc-800 rounded p-2 text-zinc-300 resize-none"
            rows={2}
          />
          <button
            onClick={handleCheck}
            disabled={!checkInput.trim()}
            className="px-3 py-1 text-[11px] bg-indigo-600 hover:bg-indigo-500 disabled:opacity-40 disabled:cursor-not-allowed text-white rounded font-semibold"
          >
            {lang === "zh-CN" ? "校验" : "Check"}
          </button>
        </div>
        {checkResult && checkResult.hasRisk && (
          <div className="mt-2 rounded border border-amber-700/40 bg-amber-900/20 p-2">
            <div className="text-[11px] text-amber-300 font-semibold mb-1">
              ⚠️ {lang === "zh-CN" ? "历史风险警告" : "History Risk Warnings"}
            </div>
            {(checkResult.warnings || []).map((w: any, i: number) => (
              <div key={i} className="text-[10px] text-amber-400 font-mono">
                • {w.message || JSON.stringify(w)}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
